version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/.github'
    schedule:
      interval: 'daily'
      time: '00:00'
    labels:
      - 'CI/CD'
    commit-message:
      prefix: 'ci'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    groups:
      ESLint:
        patterns:
          - 'typescript-eslint'
          - '@typescript-eslint/*'
      webpack:
        patterns:
          - 'webpack-*'
