name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v7'
      - name: 'Install Bun'
        uses: 'oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6'
        with:
          bun-version: 'latest'
      - name: 'Install packages'
        run: 'bun install --frozen-lockfile'
      - name: 'Build'
        run: 'bun run build'
      - name: 'Archive Artifacts'
        run: |
          zip detach-tab-chrome-${{ github.ref_name }}.zip dist-chrome/* -r
          zip detach-tab-firefox-${{ github.ref_name }}.xpi dist-firefox/* -r
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228'
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            detach-tab-chrome-${{ github.ref_name }}.zip
            detach-tab-firefox-${{ github.ref_name }}.xpi
