name: 'Release'
on:
  push:
    tags:
      - '**'
jobs:
  release:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version: ['22.x']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: 'actions/setup-node@v4'
        with:
          node-version: "${{ matrix.node-version }}"
          cache: 'npm'
      - name: 'Clean Install'
        run: 'npm ci'
      - name: 'Build'
        run: 'npm run build'
      - name: 'Archive Artifacts'
        run: |
          zip detach-tab-chrome-${{ github.ref_name }}.zip dist-chrome/* -r
          zip detach-tab-firefox-${{ github.ref_name }}.xpi dist-firefox/* -r
      - name: 'Create Release'
        uses: 'softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8'
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            detach-tab-chrome-${{ github.ref_name }}.zip
            detach-tab-firefox-${{ github.ref_name }}.xpi
